### ISSUE TITLE
Network adaptor not working on MFF 3070

### ISSUE THREAD

**Issue by sukarechhe** [ocordes/Dell_Optiplex_3060_SFF#1]
@ocordes  - 
I have tried on Ventura and works well on my MFF 3070 but one concern is that my LAN Adaptor is not working. 
Can you please help ?

**Comment by ocordes** [comment]
Sorry for the late answer, but I was on vacation ;-) 

As far as I can see the DELL 3070 series have the Realtek r8169 chip which should work with the usual Realtek driver which is also in this EFI tree. I didn't check some of these computers but a working hackintosh was reported in several forums. As far as I can see, there is nothing special in the configuration of the 3060 which is related to the Network adaptor. And I guess besides from the graphics. this EFI tree should work on a 3070 as well. What you should do in general to check if the adaptor is working, use a simple linux live distro which works out of the box with any DELL computer and check if you have LAN connection. Hope this helps!
